# Matrix
A matrix is a rectangular array of numbers or other mathematical objects with elements arranged in rows and columns. They are defined by their dimensions (m x n for m rows and n columns) and can be added, multiplied and inverted.

### A = $\begin{bmatrix} 1 & 4 & 0 & 2 \\-4 & 5 & 0 & 0\end{bmatrix}, B = \begin{bmatrix}a & b & c \\ b & d & e \\ c & e & f \end{bmatrix}$
A is 2x4 (2 rows and 4 columns) and B is 3x3 (3 rows and 3 columns) matrices 

## Uses of matrices
- Representing a linear transformation or mapping.
- Storing partial derivatives of a multivariate system.
- Representing a system of equations.
- Storing data (observation x features).
- Representing regressors for statistical modeling.
- Storing geometric transformations for computer graphics.
- Storing kernels used in filtering or convolution.

## Matrix operations
### Transpose operation
Matrix transpose is an operation that flips a matrix over its diagonals, switching its row and column indices. To transpose a matrix $\mathbf{A}$, turn its rows into columns (or vice-versa), denoted as $\mathbf{A}^T$. If the original matrix is mxn, then its transpose is nxm.

### $\mathbf{A} = \begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6\end{bmatrix}, \mathbf{A}^T = \begin{bmatrix}1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}$
$\mathbf{A}^{TT} = \mathbf{A}$

In [1]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Practice problems
Apply the transpose operator as indicated

#### a) $\begin{bmatrix}0 & 1 & 0 \\ 2 & 0 & 3\end{bmatrix}^T$ &ensp; b) $\begin{bmatrix}16 & 6 & 0 \\ 6 & 10 & -3 \\ 0 & -3 & 22\end{bmatrix}^T$ &ensp; c) $\begin{bmatrix}-1 & -3 & 1 \\ -4 & 5 & 1 \\ -5 & -4 & 6 \\ 0 & 5 & 5\end{bmatrix}^{TT}$

### Solution

#### a) &ensp; $\begin{bmatrix}0 & 2 \\ 1 & 0 \\ 0 & 3\end{bmatrix}$ &ensp; b) &ensp; $\begin{bmatrix}16 & 6 & 0 \\ 6 & 10 & -3 \\ 0 & -3 & 22\end{bmatrix}$ &ensp; c) &ensp; $\begin{bmatrix}-1 & -3 & 1 \\ -4 & 5 & 1 \\ -5 & -4 & 6 \\ 0 & 5 & 5\end{bmatrix}$

In [6]:
a = np.array([[0, 1, 0], [2, 0, 3]])
b = np.array([[16, 6, 0], [6, 10, -3], [0, -3, 22]])
c = np.array([[-1, -3, 1], [-4, 5, 1], [-5, -4, 6], [0, 5, 5]])

print(f"a:\n{a.T}")
print(f"b:\n{b.T}")
print(f"c:\n{c.T.T}")

a:
[[0 2]
 [1 0]
 [0 3]]
b:
[[16  6  0]
 [ 6 10 -3]
 [ 0 -3 22]]
c:
[[-1 -3  1]
 [-4  5  1]
 [-5 -4  6]
 [ 0  5  5]]


## Special matrices


### Square or rectangular matrices
A square matrix is a matrix that has the same number of rows as columns, thus an NxN matrix or MxN if M = N.

#### $\begin{bmatrix}0 & 1 \\ -1 & 0\end{bmatrix},$ &ensp; $\begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9\end{bmatrix}$  

A non-square matrix is called a rectangular matrix.
#### $\begin{bmatrix}0 & 1 & 2 & 3 & -5 \\ -1 & 0 & 3 & 3 & 0 \\ -2 & -3 & 0 & 0 & 0\end{bmatrix}$

### Symmetric matrices
A matrix is symmetric if it is mirrored across the diagonal, meaning the upper-right of the matrix is a flipped version of the lower-left of the matrix. Formally, a matrix is symmetric if it equal to its transpose.
#### $\mathbf{A} = \mathbf{A}^T$
Note: Only square matrix can be symmetric
#### $\begin{bmatrix}1 & 4 & 5 \\ 4 & 7 & 2 \\ 5 & 2 & 0 \end{bmatrix}$, &ensp; $\begin{bmatrix}a & b \\ b & c\end{bmatrix}$

### Identity matrix
The identity matrix is the matrix equivalent of the number 1, in that any x times 1 is x. In the case of matrices, any vector $\mathbf{v}$ times the identity matrix (indicated by $\mathbf{I}$) is that same vector $\mathbf{v}$, and any matrix $\mathbf{A}$ times $\mathbf{I}$ is still $\mathbf{A}$.

#### $\mathbf{v}\mathbf{I} = \mathbf{v}$
#### $\mathbf{A}\mathbf{I} = \mathbf{A}$

$\mathbf{I}$ is always a square matrix
#### $\mathbf{I}_2 = \begin{bmatrix}1 & 0 \\ 0 & 1\end{bmatrix}$  &ensp; $\mathbf{I}_3 = \begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{bmatrix}$

### Zeros matrices
The zeros matrix is a matrix of all zeros.

#### $\mathbf{0}_2 = \begin{bmatrix}0 & 0 \\ 0 & 0\end{bmatrix}$ &ensp; $\mathbf{0}_3 = \begin{bmatrix}0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0\end{bmatrix}$

The zeros matrix can be square or rectangular.

### Diagonal matrices
A diagonal matrix has all zeros on the off-diagonals and only the diagonal elements may contain non-zero elements.

#### $\begin{bmatrix}1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 3\end{bmatrix}$, &ensp; $\begin{bmatrix}\pi & 0 & 0 & 0 \\ 0 & e^{x^2} & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 1\end{bmatrix}$

Diagonal matrices can be square or rectangular

### Augmented matrix
An augmented matrix is the result of concatenating two or more matrices column-wise

#### $\mathbf{A} = \begin{bmatrix}1 & 4 & 2 \\ 3 & 1 & 9 \\ 4 & 2 & 0\end{bmatrix}$ &ensp; $\mathbf{B} = \begin{bmatrix}7 & 2 \\ 7 & 2 \\ 7 & 1\end{bmatrix}$ &ensp; $[A|B] = \left[\begin{array}{ccc | c} 1 & 4 & 2 & 7 & 2 \\ 3 & 1 & 9 & 7 & 2 \\ 4 & 2 & 0 & 7 & 1 \end{array}\right]$

Two matrices can be augmented only if they have the same number of rows, the number of columns need not match.

In [7]:
A = np.array([[1, 4, 2], [3, 1, 9], [4, 2, 0]])
B = np.array([[7, 2], [7, 2], [7, 1]])
AB = np.concatenate((A, B), axis=1)
AB

array([[1, 4, 2, 7, 2],
       [3, 1, 9, 7, 2],
       [4, 2, 0, 7, 1]])

### Triangular matrices
Triangular matrices comes in two forms:
- upper-triangular: only the diagonal and elements above it may contain non-zero elements
- lower-triangular: only the diagonal and elements below it may contain non-zero elements.

#### $\begin{bmatrix}1 & 8 & 4 \\ 0 & 2 & 1 \\ 0 & 0 & 9\end{bmatrix}$, &ensp; $\begin{bmatrix}1 & 0 & 0 & 0 \\ 3 & 2 & 0 & 0 \\ 6 & 5 & 9 & 0 \\ 2 & 0 & 4 & 1\end{bmatrix}$

Triangular matrices can be square or rectangular

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# extract the lower triangular part of A
np.tril(A)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [ ]:
# extract the upper triangular part of A
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

### Orthogonal
A matrix is called orthogonal if it satisfies the following criteria:
1. All of its columns are pairwise orthogonal. This means that the dot product between any two columns is exactly 0.
2. Each column is a unit magnitude.