# Vector Multiplications
There are four ways to multiply a pair of vectors which are:
1. Dot product
2. Outer product
3. Element-wise multiplication
4. Cross product

## Dot product: Algebraic
The dot product, also called inner product or scalar product is one of the basic computational building block upon which many algorithms are built such as Fourier Transform, Matrix multiplication, Correlation and so on. The result of dot product is a single number that describes the relationship between two vectors.\
To compute dot product algebraically, you multiply the corresponding elements of the two vectors and then sum over all the individual products.\
## α = $\mathbf{a} * \mathbf{b}$ = $\langle \mathbf{a}, \mathbf{b} \rangle$ = $\sum_{i=1}^{n} a_i b_i$
Dot product requires the pair of vectors to be of the same dimension

### Example
$\begin{bmatrix} 1 & 2 & 3 & 4 \end{bmatrix}$ * $\begin{bmatrix} 5 & 6 & 7 & 8 \end{bmatrix}$ = 1 X 5 + 2 X 6 + 3 X 7 + 4 X 8\
= 5 + 12 + 21 + 32\
= 70

A dot product between a vector and itself is called the sum of squared elements and is denoted by $\|\mathbf{a}\|^2$. The term $\|\mathbf{a}\|$ is called the magnitude, length or the norm of vector $\mathbf{a}$

## $\mathbf{a}^T \mathbf{a} = \|\mathbf{a}\|^2 = \sum_{i=1}^{n} a_ia_i = \sum_{i=1}^{n} a_i^2$

In [1]:
import numpy as np

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
v_dot = np.dot(v1, v2)
print(v_dot)

70


### Dot product properties
- Associativity:\
With scalar value:
### $λ(\mathbf{a}^T\mathbf{b}) = (λ\mathbf{a}^T)\mathbf{b}= \mathbf{a}^T(λ\mathbf{b}) = (\mathbf{a}^T\mathbf{b})λ$
Vector dot product does not obey associativity.
- Commutative:\
You can swap the order of vector pairs and the result will still be equal so commutative holds for vector dot product\
### $\mathbf{a}^T\mathbf{b} = \mathbf{b}^T\mathbf{a}$
- Distributive:\
Distributive holds for vector dot product.
### $\mathbf{w}^T(\mathbf{u} + \mathbf{v}) = \mathbf{w}^T\mathbf{u} + \mathbf{w}^T\mathbf{v}$

## Cauchy-Schwarz inequality
### $|\mathbf{v}^T \mathbf{w}| \le \|\mathbf{v}\| \|\mathbf{w}\|$
says that the magnitude (absolute value) of the dot product between two vectors is no larger than the product of the norms of the individual vectors

## Dot product: Geometric
The dot product is the cosine of the angle between the two vectors times the lengths of the two vectors.\
### $\mathbf{a}^T \mathbf{b} = \|\mathbf{a}\| \|\mathbf{b}\|cos(θ_{ab})$
### $cos(θ_{ab}) = \frac{\mathbf{a}^T \mathbf{b}}{\|\mathbf{a}\| \|\mathbf{b}\|}$
### $θ_{ab} = cos^{-1} (\frac{\mathbf{a}^T\mathbf{b}}{\|\mathbf{a}\|\|\mathbf{b}\|})$

## Linear Weighted Combination
Linear weighted combination is just scalar-vector multiplication and addition. It takes some set of vectors, multiply each vector by any scalar and then add them to produce a single vector.\
### $\mathbf{w} = λ_1\mathbf{v}_1 + λ_2\mathbf{v}_2 + ... + λ_n\mathbf{v}_n$
All vectors $\mathbf{v}_i$ is assumed to have the same dimension and λ can be any real number.
### Example
### $λ_1 = 1, λ_2 = 2, λ_3 = -3, \mathbf{v_1} = \begin{bmatrix} 4 \\ 5 \\ 1 \end{bmatrix}, \mathbf{v_2} = \begin{bmatrix} -4 \\ 0 \\ -4 \end{bmatrix}, \mathbf{v_3} = \begin{bmatrix} 1 \\ 3 \\ 2 \end{bmatrix}$
### $\mathbf{w} = λ_1\mathbf{v_1} + λ_2\mathbf{v_2} + λ_3\mathbf{v_3} = \begin{bmatrix} -7 \\ -4 \\ -13 \end{bmatrix}$

In [2]:
scalar_1 = 1
scalar_2 = 2
scalar_3 = -3

v1 = np.array([4, 5, 1])
v2 = np.array([-4, 0, -4])
v3 = np.array([1, 3, 2])
w = scalar_1 * v1 + scalar_2 * v2 + scalar_3 * v3
w

array([ -7,  -4, -13])

## Outer product
The outer product is a way of combining two vectors to produce a matrix. The outer product of vectors $\mathbf{v}$ and $\mathbf{w}$ is given by:
### $\mathbf{v}\mathbf{w}^T$ = M X N
The vectors do not need to be of the same dimension. There are three ways to create outer product which are:
1. Element perspective
2. Column perspective
3. Row perspective

### Element perspective
Each element i, j in the outer product matrix is the scalar multiplication between the i<sup>th</sup> element in the first vector and the j<sup>th</sup> element in the second vector.
#### Example
### $\begin{bmatrix} a \\ b \\ c \end{bmatrix} \begin{bmatrix} d & e & f \end{bmatrix} = \begin{bmatrix} ad & ae & af \\ bd & be & bf \\ cd & ce & cf \end{bmatrix}$

#### Column perspective
Each column in the outer matrix comes from repeating the left vector scaled by each element in the row vector on the right.
#### Example
### $\begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix} \begin{bmatrix} 4 & 1 & -1 \end{bmatrix} = \begin{bmatrix} 4 & 1 & -1 \\ 8 & 2 & - 2 \\ 12 & 3 & -3 \\ 16 & 4 & -4 \end{bmatrix}$

### Row perspective
Form the outer product matrix one row at a time by repeating the row vector M times, each time scaling the vector by each element in the column vector.
#### Example
### $\begin{bmatrix} 4 \\ 1 \\ -1 \end{bmatrix} \begin{bmatrix} 1 & 2 & 3 & 4 \end{bmatrix} = \begin{bmatrix} 4 & 8 & 12 & 16 \\ 1 & 2 & 3 & 4 \\ -1 & -2 & -3 & -4 \end{bmatrix}$

In [3]:
v1 = np.array([4, 1, -1])
v2 = np.array([1, 2, 3, 4])
np.outer(v1, v2)

array([[ 4,  8, 12, 16],
       [ 1,  2,  3,  4],
       [-1, -2, -3, -4]])

## Element-wise (Hadamard) product
This involves multiplying each corresponding element in the two vectors. The result is a product vector with the same size as the two multiplying vectors. It is defined only for vectors with the same number of elements (dimension).
### $\mathbf{c} = \mathbf{a}⊙\mathbf{b} = \begin{bmatrix} a_1b_1 & a_2b_2 & a_3b_3 & ... & a_nb_n \end{bmatrix}$

### Example
### $\begin{bmatrix} 3 \\ 6 \\ 9 \\ 0 \end{bmatrix} ⊙ \begin{bmatrix} 2 \\ -2 \\ 4 \\ -4 \end{bmatrix} = \begin{bmatrix} 6 \\ -12 \\ 36 \\ 0 \end{bmatrix}$

In [4]:
v1 = np.array([3, 6, 9, 0])
v2 = np.array([2, -2, 4, -4])
v1 * v2

array([  6, -12,  36,   0])

## Cross product
The cross product is defined only for two 3-element vectors and the result is a 3-element vector. The formula for computing cross product is given by:
### $\mathbf{a}$ x $\mathbf{b}$ = $\begin{bmatrix}a_2b_3 - a_3b_2 \\ a_3b_1 - a_1b_3 \\ a_1b_2 - a_2b_1\end{bmatrix}$

### Geometry
### $\|\mathbf{a}$ x $\mathbf{b}\| = \|\mathbf{a}\|\|\mathbf{b}\|sin(θ_{ab})$


## Unit vectors
A unit vector is vector with a length of 1 (i.e $\|\mathbf{a}\| = 1$)\
Creating a unit length vector is given by the formula
### $\hat{\mathbf{v}} = \frac{1}{\|\mathbf{v}\|}\mathbf{v}$

In [5]:
v = np.array([2, 5, 4, 7])
v_norm = np.linalg.norm(v)
v_unit = v / v_norm
v_unit

array([0.20628425, 0.51571062, 0.4125685 , 0.72199487])

In [6]:
np.linalg.norm(v_unit).round(1)

np.float64(1.0)

# Code challenges

## Exercise 1
Create three 5-D vectors and a
fourth vector that contains the weights for each vector. Then
create the weighted sum of those vectors. Next, modify the
code to compute the weighted mixture of four 5-D vectors.
What is the relationship between the dimensionality of the to-
be-summed vectors, the number of vectors to sum, and the
dimensionality of the coefficients vector?

In [28]:
v1 = np.random.randint(0, 10, size=5)
v2 = np.random.randint(0, 10, size=5)
v3 = np.random.randint(0, 10, size=5)
weights = [3, 5, 6]
print("v1:", v1)
print("v2:", v2)
print("v3:", v3)

v1: [2 5 1 1 8]
v2: [2 6 3 3 6]
v3: [1 7 8 8 1]


In [29]:
weighted_sum = w[0] * v1 + w[1] * v2 + w[2] * v3
print(weighted_sum)

[22 87 66 66 60]


In [30]:
v4 = np.random.randint(0, 10, size=5)
v5 = np.random.randint(0, 10, size=5)
v6 = np.random.randint(0, 10, size=5)
v7 = np.random.randint(0, 10, size=5)
w2 = [3, 5, 6, 7]
print("v4:", v4)
print("v5:", v5)
print("v6:", v6)
print("v7:", v7)

v4: [3 0 2 9 8]
v5: [4 7 1 7 4]
v6: [6 0 9 4 4]
v7: [3 0 4 4 9]


In [31]:
weighted_sum2 = w2[0] * v4 + w2[1] * v5 + w[2] * v6 + w2[3] * v7
print(weighted_sum2)

[ 86  35  93 114 131]


The relationship between the dimensionality of the to be summed vectors, the number of vectors to sum and the dimensionality of the coefficient vectors is that the dimensionality of the to be summed vectors must be of equal dimension and the dimensionality of the coefficient vectors must equal the number of vectors to sum.

## Exercise 2
Develop a method to use the dot product to compute the average of a set of numbers in a vector. (Hint: consider the vector of all ones, sometimes written 1.)

In [35]:
def average(v: np.array) -> np.float64:
    ones = np.ones_like(v)
    return np.dot(v, ones) / len(v)


v = np.array([1, 2, 3, 4])
average(v)

np.float64(2.5)

## Exercise 3
What if some numbers were more important than other numbers? Modify your answer to the previous question to devise a method to use the dot product to compute a weighted mean of a set of numbers.

In [41]:
def weighted_average(v: np.array, w: np.array) -> np.float64:
    return np.dot(v, w / np.sum(w))

w = np.random.randint(0, 10, size=v.shape[0])
print("w:", w)
print(f"Weighted average: {weighted_average(v, w):.2f}")

w: [3 0 1 8]
Weighted average: 3.17
